config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'

  resources :posts
  resources :comments, only: [:create, :new]
  resources :categories

end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_commentable

  validates :title, length: { minimum: 2, maximum: 255 }, presence: true
  validates :link, presence: true, if: :link?
  validates :link, length: { maximum: 2000 }
  validates :body, presence: true, if: :text?

  enum post_type: [:link, :text]

  belongs_to :category
  belongs_to :user
  default_scope { order('updated_at DESC').includes(:category).includes(:user) }
  scope :with_categories, -> { includes(:category) }
  scope :with_user, -> { includes(:user) }

  self.per_page = 10
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  def index
    @posts = Post.with_categories.with_user.includes(:comment_threads).page(params[:page])
  end

  def show
    @comment = Comment.build_from @post, current_user.id, ''
  end

  def edit
  end

  def new
    @post = Post.new
    @post.post_type = params[:post_type] if params[:post_type].present?
  end

  def create
    @post = Post.new( post_params )
    @post.user_id = current_user.id
    if @post.save
      redirect_to posts_path, flash: { notice: "Thanks for your submission!" }
    else
      flash.now[:error] = @post.errors.full_messages
      render :new
    end
  end

  def update
    if @post.update post_params
       redirect_to post_path, flash: { notice: "Your post has been updated." }
    else
      flash.now[:error] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    if @post.destroy
      redirect_to posts_path, flash: { notice: "Post Destroyed" }
    else
      flash.now[:error] = @post.errors.full_messages
      render :index
    end
  end


  private ##########################################################################################

  def post_params
    params.require(:post).permit( :title, :link, :body, :post_type, :category_id )
  end

  def find_post
    @post = Post.find params[:id]
  end
end

app/views/posts/_actions.html.haml
%ul.button-group.edit-buttons
  %li= link_to comment_link_text(post.comment_threads.length), post_path(post, anchor: "comments"), class: 'button tiny'
  %li.separator
  %li= link_to 'edit', edit_post_path(post), class: 'button tiny'
  %li
    = button_to "delete",
                post,
                method: :delete,
                class: 'destroy button tiny secondary',
                data: { confirm: "really?" }

app/views/posts/_form.html.haml
= form_for @post do |f|
  = f.hidden_field :post_type
  .row
    .small-12.columns= f.label :title
    .small-12.columns= f.text_field :title, placeholder: "Example: My fancy post!"
  .row
    .small-12.columns= f.label :category_id
    .small-12.columns
      = f.collection_select :category_id, Category.all, "id", "name", include_blank: true
  -if f.object.link?
    .row.collapse
      .small-12.columns= f.label :link
      .small-3.large-2.columns
        %span.prefix http://
      .small-9.large-10.columns= f.text_field :link, placeholder: "Example: lmgtfy.com"
  - elsif f.object.text?
    .row
      .small-12.columns= f.label :body
      .small-12.columns= f.text_area :body, rows: 19
  .row
    .small-12.columns
      = f.submit "Elevennit Up", class: "button medium"

app/views/posts/_post.html.haml
%h4.title
  = post_link(post)
  %br.clear
  %small{ title: post.updated_at }
    = "#{time_ago_in_words(post.updated_at).capitalize} ago by #{post.user.username} in #{link_to( post.category.name, category_path(post.category) )}".html_safe

%p= post.body if post.text?

app/views/posts/edit.html.haml
= render 'form'

app/views/posts/index.html.haml
- @posts.each do |post|
  .panel
    = render 'post', post: post
    = render 'actions', post: post
%hr
.columns.small-11.small-centered
  = will_paginate @posts, renderer: FoundationPagination::Rails
%br

app/views/posts/show.html.haml
.panel
  = render 'post', post: @post
  = render 'actions', post: @post
%hr
%h5= comment_link_text(@post.comment_threads.count)
#comments
  = nested_posts @post.comment_threads, id: 'comments' do |comment|   
    .panel{ id: "reply-#{comment.id}"}
      = comment.body
      = link_to 'Reply to this comment',
                new_comment_path(parent_id: comment.id, format: 'js'),
                remote: true,
                class: 'button tiny secondary'
      %div.reply-form.hide{ id: "reply-form-#{comment.id}" }

= render 'comments/form'