config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'

  resources :posts
  resources :comments, only: [:create, :new]
  resources :categories

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, uniqueness: true, presence: true, length: { minimum: 2, maximum: 20 }
  validates :title, length: { maximum: 100 }
  validates :description, length: { maximum: 500 }
  validates :sidebar, length: { maximum: 5120 }
  validates :submission_text, length: { maximum: 1024 }

  has_many :posts
  default_scope { order('lower(name) ASC') }
  scope :added_today, -> { where('created_at > ?', Time.now.beginning_of_day) }
  scope :added_after, -> (time) { where('created_at > ?', time) }
end


# LAMBDA EXAMPLES BELOW
# class User < ActiveRecord::Base
#   scope :active, -> { where(active: true) }
#   scope :admin, -> { where(user_type: 'admin') }
# end

app/models/concerns/category.rb
class Post < ActiveRecord::Base
  validates :name, uniqueness: true, presence: true, length: { minimum: 2, maximum: 20 }
  validates :title, length: { minimum: 2, maximum: 100 }
  validates :description, length: { minimum: 2, maximum: 500 }
  validates :sidebar, length: { maximum: 5120 }
  validates :submission_text, length: { maximum: 5120 }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: [:edit, :update, :destroy]

  def index
  end

  def show
    @category = Category.includes(posts: [:comment_threads]).find(params[:id])
    @posts = @category.posts.page(params[:page])
  end

  def edit
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new( category_params )
    if @category.save
      redirect_to categories_path, flash: { notice: "Thanks for your submission!" }
    else
      flash.now[:error] = @category.errors.full_messages
      render :new
    end
  end

  def update
    if @category.update category_params
       redirect_to category_path, flash: { notice: "Your category has been updated." }
    else
      flash.now[:error] = @category.errors.full_messages
      render :edit
    end
  end

  def destroy
    if @category.destroy
      redirect_to categories_path, flash: { notice: "Category Destroyed" }
    else
      flash.now[:error] = @category.errors.full_messages
      render :index
    end
  end
  private ##########################################################################################

  def category_params
    params.require(:category).permit( :name, :title, :description, :sidebar, :submission_text )
  end

  def find_category
    @category = Category.find params[:id]
  end
end

app/views/categories/_actions.html.haml
%ul.button-group.edit-buttons
  %li= link_to 'edit', edit_category_path(category), class: 'button tiny'
  %li
    = button_to "delete",
                category,
                method: :delete,
                class: 'destroy button tiny secondary',
                data: { confirm: "really?" }

app/views/categories/_category.html.haml
%h4.title
  = link_to category.name, category
  %small= category.title

%p= category.description if category.description?

= render 'actions', category: category

app/views/categories/_form.html.haml
= form_for @category do |f|
  .row
    .small-12.columns= f.label :name
    .small-12.columns= f.text_field :name, placeholder: "Adorable Cats"
  .row
    .small-12.columns= f.label :title
    .small-12.columns= f.text_field :title, placeholder: "Example: My fancy category!"
  .row
    .small-12.columns= f.label :description
    .small-12.columns= f.text_area :description
  .row
    .small-12.columns= f.label :sidebar
    .small-12.columns= f.text_field :sidebar, placeholder: "Descriptive text for the sidebar"
  .row
    .small-12.columns= f.label :submission_text
    .small-12.columns= f.text_field :submission_text, placeholder: "I don't know what this is."
  .row
    .small-12.columns
      = f.submit "Elevennit Up", class: "button medium"

app/views/categories/edit.html.haml
= render 'form'

app/views/categories/index.html.haml
%h3 Categories
- @categories.each do |category|
  .panel
    = render 'category', category: category

app/views/categories/new.html.haml
= render 'form'

app/views/categories/show.html.haml
= sidebar( @category.sidebar )
.panel
  = render 'category', category: @category

.panel
  %h3.title Posts in this Category
  %hr
  - @posts.each do |post|
    =render 'posts/post', post: post
  %hr
  = will_paginate @posts, renderer: FoundationPagination::Rails