config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'

  resources :posts
  resources :comments, only: [:create, :new]
  resources :categories

end

app/views/layouts/application.html.erb
!!!
%html
  %head
    %meta{ charset: "utf-8" }
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }
    %title= content_for?(:title) ? yield(:title) : "foundation-rails"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
  %body
    = yield
    = javascript_include_tag "application"

app/views/layouts/application.html.haml
!!!

%html
  %head
    %meta{ charset: "utf-8" }
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }
    %title= content_for?(:title) ? yield(:title) : "foundation-rails"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
  %body
    %header.fixed
      %ul.breadcrumbs
        %li.with-dropdown
          = link_to "categories",
                    "#",
                    class: 'button dropdown secondary tiny',
                    data: { dropdown: 'drop' }
          %ul#drop.f-dropdown{ data: { dropdown: { content: true } } }
            - @categories.each do |category|
              %li= link_to category.name, category
        - @categories.each do |category|
          %li= link_to category.name, category
      %nav.top-bar{ data: { topbar: true }, role: "navigation" }
        %ul.title-area
          %li.name
            %h1
              %span.left= image_tag "reddit_alien.png"
              %span.left= link_to "Elevennit", posts_url
        .right.has-dropdown.user-menu
          - if user_signed_in?
            = link_to current_user.username, "#", class: 'dropdown', data: { dropdown: 'user-drop' }
            %ul#user-drop.f-dropdown{ data: { dropdown: { content: true } } }
              %li= link_to 'manage account', edit_user_registration_path(current_user.id)
              %li= link_to 'logout', destroy_user_session_path, method: :delete
          - else
            = link_to 'login', new_user_session_path


    %section.row
      .columns.small-12.medium-8
        - flash.each do |name, msg|
          .alert-box{ class: "#{flash_class name}", data: { alert: true } }
            - if msg.is_a? Array
              = msg.join("<br>").html_safe
            - else
              = msg.html_safe
            = link_to '&times;'.html_safe, '#', class: 'close'
        = yield
      %sidebar.columns.medium-4.hide-for-small
        - if content_for?(:sidebar)
          .panel= yield :sidebar
        .text-center
          = link_to 'new post', new_post_path(post_type: :text), class: 'button small-12'
          = link_to 'share link', new_post_path(post_type: :link), class: 'button small-12'
          = link_to 'add category', new_category_path, class: 'button small-12'
    %footer.fixed
      %nav.top-bar{ data: { topbar: true }, role: 'navigation' }
        %p= "&copy; #{Time.now.year} Random Tutorials Productions".html_safe


    = javascript_include_tag "application"